# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-17 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiuyanModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('message', models.CharField(max_length=600, verbose_name='留言')),
                ('add_time', models.DateTimeField(auto_now=True, verbose_name='添加时间')),
            ],
        ),
    ]
